name : HCM-Build-Scratch-Org

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "Package version in format major.minor, eg: 27.1"
        type: string
        required: true  
      branchName:
        description: "Branch name"
        required: false
        default: "main"             

jobs:
  Create_Package:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:          

      - name: Install Salesforce SFDX
        run: |
          npm install -g sfdx-cli
          
      - name: "Authorise Packaging org"
        run: |
          echo "${{ secrets.RICO_PACKAGING_ORG_SERVER_KEY }}" > "server.key"
          sfdx force:auth:jwt:grant --client-id=${{ secrets.RICO_PACKAGING_ORG_CONSUMER_KEY }} --username=${{ secrets.RICO_PACKAGING_ORG_USERNAME }} --jwt-key-file ./server.key
          sfdx force:config:set -g defaultusername=${{ secrets.RICO_PACKAGING_ORG_USERNAME }}

      - uses: actions/checkout@v3
        name: Checkout Project
        with:
          ref: ${{ inputs.branchName }}
          token: ${{ secrets.RICO_PACKAGING_ORG_GITHUB_TOKEN }}
        
      - name: "Deploy Packaging org"
        run: |
          sfdx force:source:convert --sourcepath=force-app --outputdir package
          sfdx force:mdapi:deploy --deploydir package --targetusername ${{ secrets.RICO_PACKAGING_ORG_USERNAME }} --wait 10
      
      - name: "Set github variables"
        run: |
          git config --global user.email "robertoricofernandez@gmail.com"
          git config --global user.name "Rico"

      - name: create tags
        run: |
          git tag -a ${{ inputs.packageVersion }} -m "${{ inputs.packageVersion }}" 
          git push origin --tags

      - name: build package version
        run: |
          sfdx package1:version:create --package-id "0338d000000E6DqAAK" --name "${{ inputs.packageVersion }}" --version ${{ inputs.packageVersion }} --managedreleased -w 10

